version: "3"
services:
  es:
    image: elasticsearch:5.6.12
    ports:
    - 9200:9200
    volumes:
    - ./es-data:/usr/share/elasticsearch/data
  web:
    build: ./
    ports:
    - 9201:9201
     